CREATE TABLE IF NOT EXISTS Comir(
    IdComir INT UNSIGNED AUTO_INCREMENT,
	MirName VARCHAR(50) NOT NULL,
	GeneID VARCHAR(50) NOT NULL,
	GeneSymbol VARCHAR(50),
	Score FLOAT,
	PRIMARY KEY (IdComir)
);