CREATE TABLE IF NOT EXISTS Mirecords(
    IdMirecords INT UNSIGNED AUTO_INCREMENT,
	MirName VARCHAR(50) NOT NULL,
	GeneID VARCHAR(50) NOT NULL,
	GeneSymbol VARCHAR(50),
	Experiment LONGTEXT,
	PRIMARY KEY (IdMirecords)
);

ALTER TABLE Mirecords CONVERT TO CHARACTER SET utf8;