CREATE TABLE IF NOT EXISTS Mirtarbase(
    IdMirtarbase INT UNSIGNED AUTO_INCREMENT,
	MirName VARCHAR(50) NOT NULL,
	GeneID VARCHAR(50) NOT NULL,
	GeneSymbol VARCHAR(50),
	Experiment LONGTEXT,
	PRIMARY KEY (IdMirtarbase)
);

ALTER TABLE Mirtarbase CONVERT TO CHARACTER SET utf8;

