CREATE TABLE IF NOT EXISTS Mirwalk(
    IdMirwalk INT UNSIGNED AUTO_INCREMENT,
	MirName VARCHAR(50) NOT NULL,
	GeneID VARCHAR(50) NOT NULL,
	GeneSymbol VARCHAR(50),
	Score FLOAT,
	PRIMARY KEY (IdMirwalk)
);